### ISSUE TITLE
Cannot list COM Ports

### ISSUE THREAD

**Issue by nsiatras** [java-native/jssc#170]
Hello,

I am using ``` String[] serialPorts = SerialPortList.getPortNames();``` to get a list of the COM ports of the computer.
This method works correctly and always returns the available COM ports of the PC.

Today I tested my software on a Lenovo desktop computer running Windows 10 and the result was missing a Port.
The computer had an ESP32 Node MCU connected to **COM11** but the result was missing that port. In fact the result was **COM1**

The ESP32 is connected correctly to the computer and I can send and receive data from it.

Have you ever noticed this problem again ?

**Comment by tresf** [comment]
> Have you ever noticed this problem again ?

No.  I assume rebooting the computer didn't fix it either?  

The native code is here:

https://github.com/java-native/jssc/blob/8dd99a4e6a945b29db4709ffd4dcdf80770068de/src/main/cpp/windows/jssc.cpp#L644-L688

**Comment by nsiatras** [comment]
Correct. We also formatted and re-installed windows with the same results

**Comment by nsiatras** [comment]
Well... the issue in my case are the drivers.

With the 11.3.0.176 (13-Apr-23) drivers for the CP210x USB to UART the port can be listed.
but with the 11.4.0.317 (19-Jul-24) version for the drivers the port cannot be listed...
![Drivers](https://github.com/user-attachments/assets/0ae5e17b-3be6-4107-bdbb-709931bebf6c)

**Comment by nsiatras** [comment]
**Better Issue Description:**
We recently upgraded the Windows version of the CP210x USB to UART Bridge drivers from version **11.3.0.176** to **11.4.0.317**
Link to drivers: https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads

After the drivers update we are not able to correctly list the COM ports of the computer using the Java jssc 
To be more specific after calling the ```String[] serialPorts = SerialPortList.getPortNames();``` the result is an empty array.

The serial communication with the device works correctly the only problem is that the COM port cannot be listed.

**Comment by tresf** [comment]
@nsiatras,

@hiddenalpha has kindly provided a potential patch here: #171 can you test it?  Here's a compile from my machine:

[jssc-2.9.7-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16531297/jssc-2.9.7-SNAPSHOT.jar.zip)

**Comment by nsiatras** [comment]
Hello,

I get the following exception:

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/scijava/nativelib/JniExtractor
	at jssc.SerialPortList.<clinit>(SerialPortList.java:49)
	
Caused by: java.lang.ClassNotFoundException: org.scijava.nativelib.JniExtractor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 29 more

**Comment by tresf** [comment]
> Hello,
> 
> I get the following exception:

Sorry, the build is missing this dependency.  I'll try to make a fat jar containing this...

**Comment by tresf** [comment]
@nsiatras OK, this one should have the scijava dependencies included, can you please test?

[jssc-2.9.7-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16550734/jssc-2.9.7-SNAPSHOT.jar.zip)

**Comment by nsiatras** [comment]
I just tested the snapshot.
No exceptions on this one and data exchange works still correct but I still cannot list the COM ports correctly.

**Comment by pietrygamat** [comment]
@nsiatras you may want to check that the driver parameter `SerialSkipExternalNaming` is not set in you Windows machine
```
regedt -> Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\silabser\Parameters
```
![image](https://github.com/user-attachments/assets/2bd7b0bf-6c4e-40b1-bdd1-22c3a0a764fb)
and if it is - remove the key, then reboot the PC (or at least reconnect the device).
```
SETUP REGISTRY KEY
------------------
Registry keys are used for setting some parameters of the serial port
For setting these parameters, we have 2 ways:
	- Modify registry value using registry editor of Windows
	- Modify registry value using INF file
The detail of each method as following.
### Modify registry value using registry editor of Windows ###

1. Edit the file UpdateParameters.reg according to your settings, save the file.
   Registry keys are allocated at 3 position:
   - Parameters keys: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\silabser
   - Software keys:   HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\<ClassID>\
   - Hardware keys:   HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\USB\deviceID\
2. Right-click to UpdateParam.bat -> run as administrator, then your settings have been updated.
3. Restart you computer.
```
[source](https://www.silabs.com/documents/public/release-notes/CP210x_Universal_Windows_Driver_ReleaseNotes.txt)

**Comment by nsiatras** [comment]
Hello,

I reported this issue on the SiliconLabs forum and I just get the following reply:

"*This behavior might be affected by some changes in the new VCP 11.4 driver. The Old VCP 11.3 will be back on the website for downloading.

I will let you know if I have any updates on it. Again, Thanks for your information*"

https://community.silabs.com/s/question/0D7Vm000003SrZ7KAK/detail?language=en_US
