### ISSUE TITLE
UnsatisfiedLinkException NOT thrown

### ISSUE THREAD

**Issue by tresf** [java-native/jssc#29]
When running the SNAPSHOT from a local build in a Java project with a missing library (no DLL, no and calling `SerialPortList.getPortNames();`, the software does NOT throw an `UnsatisfiedLinkError` but it must.

```java
import jssc.SerialPortList;

import java.util.Arrays;

public class Main {
    public static void main(String ... args) {
        System.out.println(Arrays.toString(SerialPortList.getPortNames()));
    }
}
```

Output:

```
[]
```

This should raise an exception and NOT continue.  This is a regression.

**Comment by tresf** [comment]
Nevermind, was not testing correctly.  It's throwing it.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load the jssc library: Couldn't load library library jssc
	at jssc.SerialNativeInterface.<clinit>(SerialNativeInterface.java:81)
	at jssc.SerialPortList.<clinit>(SerialPortList.java:43)
	at Main.main(Main.java:7)
```
