### ISSUE TITLE
cant run jar generated by maven

### ISSUE THREAD

**Issue by erikLundstedt** [java-native/jssc#72]
ide:intelij comunity edition
os:debian
compiled by maven

/home/erik/.jdks/adopt-openjdk-1.8.0_265/bin/java -Dfile.encoding=UTF-8 -jar /home/erik/git/projects/arduino/projects/rgbStuff/riderPixels/java/riderPixelsV2Controller/target/pixelController1.0.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: jssc/SerialPortException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: jssc.SerialPortException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

**Comment by erikLundstedt** [comment]
<dependency>
			<groupId>com.fazecast</groupId>
			<artifactId>jSerialComm</artifactId>
			<version>[2.0.0,3.0.0)</version>
		</dependency>
		<dependency>
			<groupId>io.github.java-native</groupId>
			<artifactId>jssc</artifactId>
			<version>2.9.2</version>
		</dependency>

**Comment by erikLundstedt** [comment]
i tried installing the jni library
sudo apt-get install librxtx-java
still giving the same error

**Comment by JockX** [comment]
The classes are definitely included. It looks to me you are trying to run your project's jar alone, without adding its dependencies in the classpath. Is this you wanted:
https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven ?
